config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root "devise/sessions#new"
  end

  resources :shifts, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
  end
  
  resources :user, only: [:show, :edit, :update]do
    resources :shifts
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
  validates :start_time, :out_time, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
  has_many :shifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

  def after_sign_in_path_for(resource)
    shifts_path
  end
end

app/controllers/shift_controller.rb
class ShiftController < ApplicationController

  def index
    
    @user = User.find(1)
  end
  
  def show
    @shifts = Shift.all
  end

  def new
    @shift = Shift.new
  end

  def create
    Shift.create(shift_params)
    redirect_to shift_path
  end

  private

  def shift_params
    params.require(:shift).permit(:date, :start_time, :end_time, :user_id)
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  before_action :authenticate_user!

  def index
    @shifts = Shift.all
  end
  
  def show
    @users = User.all
    @shift = Shift.find(params[:id])
  end

  def new
    @shift = Shift.new
  end

  def create
    Shift.create(shift_params)
    redirect_to shifts_path
  end

  def edit
    @shift = Shift.find(params[:id])
  end

  def update
    @shift = Shift.find(params[:id])
    if @shift.update(shift_params)
      redirect_to shifts_path
    else
      render 'edit'
    end
  end

  def destroy
    @shift = Shift.find(params[:id])
    @shift.destroy
    redirect_to root_path, notice:"削除しました"
  end


  private

  def shift_params
    params.require(:shift).permit(:start_time, :out_time).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShiftApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="header">
  <%= link_to root_path, class: 'header-link' do %>
    <h1>Shift-app</h1>

    <%= link_to destroy_user_session_path, method: :delete do %>
      <button type="button" class="btn btn-danger">ログアウト</button>
    <% end %>
  <% end %>


</div>

app/views/shared/_header2.html.erb
<div class="header">
  <h1>Shift-app</h1>
</div>

app/views/shift/new.html.erb
<div class="main">
  <%= render partial: 'shared/header' %>
  <div class="main-new">
    <div class="inner">
      <div class="inner-content">
        <%= form_with model: @shift, :url => { :controller => :shift, :action => :create } do |f| %>
          <h2>シフト登録</h2>
          <h3>勤務日入力</h3>
          <div><%= f.date_field :date, class: "input-date" %></div>
          <h3>出勤時刻</h3>
          <div><%= f.time_field :start_time, class: "input-start" %></div>
          <h3>退勤時刻</h3>
          <div><%= f.time_field :end_time, class: "input-end" %></div>
          <div><%= f.submit "登録", class: "submit-btn" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shift/show.html.erb
<% if false %>
   <div class="main">
    <%= render partial: 'shared/header' %>
    <%= link_to new_shift_path do %>
      <button type="button" class="btn btn-primary">シフト提出</button></a>
    <% end %>
    <button type="button" class="btn btn btn-warning">シフト編集</button>
    <%= month_calendar do |date| %>
      <%= date.day %>
    <% end %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<div class="main">
  <%= render partial: 'shared/header' %>
  <div class="main-new">
    <div class="inner">
      <div class="inner-content">
        <%= form_with(model: @shift, local: true) do |f| %>
          <h2>シフト登録</h2>
          <h3>勤務日入力</h3>
          <div><%= f.datetime_field :start_time, class: "input-date" %></div>
          <h3>退勤時刻</h3>
          <div><%= f.time_field :out_time, class: "input-end" %></div>
          <div><%= f.submit "登録", class: "submit-btn" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shifts/index.html.erb
<div class="main">
  <%= render partial: 'shared/header' %>
  <%= link_to new_shift_path do %>
    <button type="button" class="btn btn-primary">シフト提出</button>
  <% end %>
  <button type="button" class="btn btn btn-warning">シフト編集</button>

  <%= month_calendar events: @shifts do |date, shifts| %>
    <%= date.day %>

    <% shifts.each do |shift| %>
      <div>
        <%= shift.user.name %>
        <%= link_to shift.start_time.to_s(:time), shift %>〜
      </div>
    <% end %>
  <% end %>
</div>

app/views/shifts/new.html.erb
<div class="main">
  <%= render partial: 'shared/header' %>
  <div class="main-new">
    <div class="inner">
      <div class="inner-content">
        <%= form_with(model: @shift, local: true) do |f| %>
          <h2>シフト登録</h2>
          <h3>勤務日入力</h3>
          <div><%= f.datetime_field :start_time, class: "input-date" %></div>
          <h3>退勤時刻</h3>
          <div><%= f.time_field :out_time, class: "input-out" %></div>
          <div><%= f.submit "登録", class: "submit-btn" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shifts/show.html.erb
<div class="main">
  <%= render partial: 'shared/header' %>
  <div class="main-show">
    <div class="inner">
      <div class="inner-content">
        <h2>勤務日</h2>
        <div>
          <%= @shift.start_time.strftime("%Y-%m-%d") %>
        </div>
        <h2>勤務時刻</h2>
        <div>
          <%= @shift.start_time.strftime("%H:%M") %>〜
          <%= @shift.out_time.to_s(:time) %>
        </div>
        <% if user_signed_in? && current_user.id == @shift.user.id %>
          <div class="shift-links">
            <%= link_to edit_shift_path(@shift), class: "edit-link" do %>
              <button type="button" class="btn btn-warning">編集する</button>
            <% end %>
            <%= link_to shift_path(@shift), class: "destroy-link", method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } do %>
              <button type="button" class="btn btn-danger">削除する</button>
            <% end %>
        <% end %>
            <%= link_to shifts_path, class: "back-link" do %>
              <button type="button" class="btn btn-light">戻る</button>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '次月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>